### ISSUE TITLE
Cargo Embed Silently Fails With Specific USB Device Plugged In

### ISSUE THREAD

**Issue by great-houk** [probe-rs/cargo-embed#303] opened 2022-01-23 20:21 UTC
**Describe the bug**
When I plug in my usb mic cargo flash silently fails, producing some compiler output but never flashing the device (micro:bit V2). I am compiling and flashing the rust embedded book's verify code, under src-03.

**To Reproduce**
1. Plug In USB Mic (https://www.amazon.com/gp/product/B07GQT8879)
2. Run Cargo flash or embed with any program
3. No flashing happens, and no errors are reported

**Expected behavior**
The device should be flashed with the program, but it is not.

**Stacktrace**
Running cargo flash with logs enabled shows some things, but since no errors are reported, there is not much to put
"cargo flash --list-probes --log trace" without mic
       DEBUG probe_rs::probe::cmsisdap::tools > Searching for CMSIS-DAP probes using libusb
       TRACE probe_rs::probe::cmsisdap::tools > CMSIS-DAP v1: CMSIS-DAP device with 6 interfaces
       TRACE probe_rs::probe::cmsisdap::tools > Interface 0 is not HID, skipping
       TRACE probe_rs::probe::cmsisdap::tools > Interface 1 is not HID, skipping
       TRACE probe_rs::probe::cmsisdap::tools > Interface 2 is not HID, skipping
       TRACE probe_rs::probe::cmsisdap::tools >   Interface 3: CMSIS-DAP v1
       TRACE probe_rs::probe::cmsisdap::tools > Will use interface number 3 for CMSIS-DAPv1
       DEBUG probe_rs::probe::cmsisdap::tools > Found 1 CMSIS-DAP probes using libusb, searching HID
       TRACE probe_rs::probe::cmsisdap::tools > CMSIS-DAP device with USB path: "\\\\?\\hid#vid_0d28&pid_0204&mi_03#b&7af8a72&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}"
       TRACE probe_rs::probe::cmsisdap::tools >                 product_string: "CMSIS-DAP v1"
       TRACE probe_rs::probe::cmsisdap::tools >                      interface: 3
       TRACE probe_rs::probe::cmsisdap::tools > Ignoring duplicate CMSIS-DAP v1 (VID: 0d28, PID: 0204, Serial: 990536020005283389441cd3abf11b0f000000006e052820, CmsisDap)
       DEBUG probe_rs::probe::cmsisdap::tools > Found 1 CMSIS-DAP probes total
       DEBUG jaylink                          > libusb 1.0.24.11584
       DEBUG jaylink                          > libusb has capability API: true
       DEBUG jaylink                          > libusb has HID access: true
       DEBUG jaylink                          > libusb has hotplug support: false
       DEBUG jaylink                          > libusb can detach kernel driver: false
The following debug probes were found:
[0]: CMSIS-DAP v1 (VID: 0d28, PID: 0204, Serial: 990536020005283389441cd3abf11b0f000000006e052820, CmsisDap)

"cargo flash --list-probes --log trace" with mic
       DEBUG probe_rs::probe::cmsisdap::tools > Searching for CMSIS-DAP probes using libusb
       TRACE probe_rs::probe::cmsisdap::tools > CMSIS-DAP v1: CMSIS-DAP device with 6 interfaces
       TRACE probe_rs::probe::cmsisdap::tools > Interface 0 is not HID, skipping
       TRACE probe_rs::probe::cmsisdap::tools > Interface 1 is not HID, skipping
       TRACE probe_rs::probe::cmsisdap::tools > Interface 2 is not HID, skipping
       TRACE probe_rs::probe::cmsisdap::tools >   Interface 3: CMSIS-DAP v1
       TRACE probe_rs::probe::cmsisdap::tools > Will use interface number 3 for CMSIS-DAPv1

**Desktop (please complete the following information):**
 - Windows 11 21H2

**Additional context**
I am using an AMD Ryzen 5 2600X, running all the latest updates for rustc, binutils, cargo-embed, and cargo-flash

**Comment by Yatekii** [comment] 2022-01-23 23:25
Unfortunately this is a bug in `libusb` we have no control over.

This is a duplicate of https://github.com/probe-rs/probe-rs/issues/935.

**Closed by Yatekii** 2022-01-23 23:25 UTC
Labels: bug
