### ISSUE TITLE
ATSAMD21G18A (Arduino MKR1000) No connected probes were found

### ISSUE THREAD

**Issue by Maik93** [probe-rs/cargo-embed#371] opened 2022-08-20 16:54 UTC
I'm not able to flash an Arduino MKR1000, neither with `probe-run --chip ATSAMD21G18A` or `cargo embed`.
The output log always states `Error No connected probes were found.`
The same board behaves normally in Arduino IDE (I'm able to flash it).

**To Reproduce**
1. Start from the [example](https://github.com/atsamd-rs/atsamd/tree/master/boards/arduino_mkr1000) blink;
2. Uncomment `runner = 'probe-run --chip ATSAMD21G18A'` inside `.cargo/config`
3. Execute `cargo run`

**Stacktrace**
```
warning: use of deprecated associated function `arduino_mkr1000::gpio::Pin::<I, M>::into_open_drain_output`: The gpio::v1 module is deprecated, and will be removed in a subsequent release.
             Please use the gpio::v2 module instead.
  --> src/main.rs:30:27
   |
30 |     let mut led = pins.d6.into_open_drain_output(&mut pins.port);
   |                           ^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: `mkr1000_blink` (bin "mkr1000_blink") generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `probe-run --chip ATSAMD21G18A target/thumbv6m-none-eabi/debug/mkr1000_blink`
Error: no probe was found.
```

**Environment**
 - Archlinux
 - udev rules installed, `/dev/ttyACM0` correctly recognised as the target board.
 - Board is functional with Arduino IDE

**Comment by Yatekii** [comment] 2022-08-20 17:26
The Arduino IDE uses a Bootloader over UART (/dev/ttyACM0) which can only flash and log. This is enough for most usecases.
But probe-rs is a fully fledged debug library which requires a special debug probe to talk to the target, as is required to programm any chip, at least the first time (for Arduino they do this in the factory).
This is why this does not work for you. You will need to get a debug probe and connect it to your chip to make it work with probe-rs :)

I am closing this because this works as intended, but feel free to ask further questions or drop by in the Matrix channel for more help :)

**Closed by Yatekii** 2022-08-20 17:26 UTC
Labels: bug
